apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: h2databases.h2.example.com
spec:
  group: h2.example.com
  names:
    kind: H2Database
    listKind: H2DatabaseList
    plural: h2databases
    singular: h2database
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: H2Database is the Schema for the h2databases API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: H2DatabaseSpec defines the desired state of H2Database
          properties:
            backup:
              description: URL to which the operator should POST DB backups, leave
                as 'skip' string if you don't want backups
              type: string
            clustering:
              description: Indicate whether to try to run the DBs as a connected cluster;
                will only be considered when there are exactly two DB instances running
                (since H2 demands it); 'yes' or 'no'
              type: string
            size:
              description: 'Size is the size of the h2 deployment Imporant: having
                more that 2 pods in the deplyoment is probably not necessary, as currently
                H2 only supports running on a single node or in HA mode with a cluster
                of size 2'
              format: int32
              type: integer
          required:
          - backup
          - clustering
          - size
          type: object
        status:
          description: H2DatabaseStatus defines the observed state of H2Database
          properties:
            nodes:
              description: Nodes are the names of the h2 pods
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
