apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-operators-project
spec:
  replicas: 1
  selector:
    matchLabels:
      name: kubernetes-operators-project
  template:
    metadata:
      labels:
        name: kubernetes-operators-project
    spec:
      serviceAccountName: kubernetes-operators-project
      containers:
        - name: kubernetes-operators-project
          # Replace this with the built image name
          image: pwegrzyndocking/kubernetes-operators-project
          command:
          - kubernetes-operators-project
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "kubernetes-operators-project"
